/**
 * Export a SysML v2 block as an FMU — an FMI 3.0 `.fmu` archive containing the
 * generated `modelDescription.xml`. This is an INTERFACE / co-simulation-scaffold
 * FMU: it carries the full, valid model description (variables, causality, units,
 * model structure) so external FMI tools can inspect it, wire it up, and (with a
 * generated binary) co-simulate it. No platform binary is bundled — the browser
 * can't compile one — so the archive is a description-complete skeleton.
 */

import { type ElementId, type Model } from '@core/index';
import {
  fmiModelDescription,
  type FmiExportOptions,
  type FmiModelDescription,
} from './model-description';
import { zipStore } from './zip';
import { PRODUCT_NAME } from '../../branding';

/** The result of an FMU export: the archive bytes + its suggested file name. */
export interface FmuExport {
  /** Suggested `.fmu` file name (`<modelIdentifier>.fmu`). */
  fileName: string;
  /** The `.fmu` archive bytes (a STORED ZIP). */
  data: Uint8Array;
  /** The generated model description (for inspection / the `.xml` download). */
  description: FmiModelDescription;
}

/**
 * Build an FMU (`.fmu` archive) for the block `blockId`. The archive contains
 * `modelDescription.xml` at its root, plus a short generation note under
 * `documentation/`.
 */
export function exportFmu(model: Model, blockId: ElementId, opts: FmiExportOptions = {}): FmuExport {
  const description = fmiModelDescription(model, blockId, opts);
  const enc = new TextEncoder();
  const readme =
    `${description.modelName} — FMI 3.0 co-simulation FMU (interface skeleton).\n` +
    `Generated by ${PRODUCT_NAME} from block ${blockId}.\n` +
    `Contains modelDescription.xml only; add a platform binary to run it.\n`;
  const data = zipStore([
    { name: 'modelDescription.xml', data: enc.encode(description.xml) },
    { name: 'documentation/generated.txt', data: enc.encode(readme) },
  ]);
  return { fileName: `${description.modelIdentifier}.fmu`, data, description };
}
