import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath, URL } from 'node:url';
import { createHash } from 'node:crypto';

/**
 * Emit a versioned service worker (`dist/sw.js`) that atomically precaches the
 * boot SHELL — index.html + the entry chunk + its static-import chunks + their
 * CSS — so the app loads offline as a self-consistent unit even across deploys.
 * The cache name embeds a hash of the shell file list, so `activate` purges the
 * previous version's cache on every redeploy (no unbounded growth). Lazy view
 * chunks and the ~8MB `stdlib.json` data asset are intentionally NOT precached;
 * they load + cache at runtime (best-effort offline). Runtime strategy stays
 * network-first (transparent while online).
 */
function pwaServiceWorker(): Plugin {
  return {
    name: 'pwa-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const entry = Object.values(bundle).find((c) => c.type === 'chunk' && c.isEntry);
      const shell = new Set<string>();
      if (entry && entry.type === 'chunk') {
        const seen = new Set<string>();
        const visit = (name: string): void => {
          if (seen.has(name)) return;
          seen.add(name);
          const c = bundle[name];
          if (!c || c.type !== 'chunk') return;
          shell.add(name);
          for (const css of (c as unknown as { viteMetadata?: { importedCss?: Set<string> } })
            .viteMetadata?.importedCss ?? [])
            shell.add(css);
          for (const imp of c.imports) visit(imp);
        };
        visit(entry.fileName);
      }
      // index.html first: it's the navigate-offline fallback.
      const list = ['index.html', ...[...shell].sort()];
      const version = createHash('sha256').update(list.join(',')).digest('hex').slice(0, 12);
      const sw = `/* Auto-generated by vite.config pwaServiceWorker — do not edit. */
const CACHE = 'sysmlv2-${version}';
const SHELL = ${JSON.stringify(list)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    fetch(req)
      .then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {}); return res; })
      .catch(() => caches.match(req).then((c) => c || (req.mode === 'navigate' ? caches.match('index.html') : Response.error())))
  );
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: sw });
    },
  };
}

export default defineConfig({
  // Relative base so the static build works on any host path (GitHub Pages
  // subpath, a plain file server, or the root) without reconfiguration.
  base: './',
  plugins: [react(), pwaServiceWorker()],
  resolve: {
    alias: {
      '@core': fileURLToPath(new URL('./src/core', import.meta.url)),
      '@text': fileURLToPath(new URL('./src/text', import.meta.url)),
      '@api': fileURLToPath(new URL('./src/api', import.meta.url)),
      '@validation': fileURLToPath(new URL('./src/validation', import.meta.url)),
      '@persistence': fileURLToPath(new URL('./src/persistence', import.meta.url)),
      '@diagram': fileURLToPath(new URL('./src/diagram', import.meta.url)),
      '@ui': fileURLToPath(new URL('./src/ui', import.meta.url)),
      '@semantics': fileURLToPath(new URL('./src/semantics', import.meta.url)),
      '@library': fileURLToPath(new URL('./src/library', import.meta.url)),
      '@collab': fileURLToPath(new URL('./src/collab', import.meta.url)),
      '@interop': fileURLToPath(new URL('./src/interop', import.meta.url)),
      '@server': fileURLToPath(new URL('./src/server', import.meta.url)),
    },
  },
  server: { port: 5173, strictPort: true },
  // Minification is ON (esbuild). It was previously disabled because the ~8MB
  // standard library was pulled into a JS chunk (a dynamic-imported ~8MB module)
  // and vite's build-import-analysis (es-module-lexer) failed to re-parse that
  // giant minified chunk ("Parse error @:1:1"). The library now ships as a
  // FETCHED DATA ASSET (see `src/library/full-library.ts` — referenced via
  // `new URL('./std/stdlib.json', import.meta.url)`, emitted as
  // `dist/assets/stdlib-<hash>.json` outside the JS graph), so the remaining JS
  // chunks are normal-sized and minify cleanly.
  build: {
    outDir: 'dist',
    // Clear stale chunks from prior builds so `dist/assets/` doesn't accumulate
    // orphaned hashed files between builds.
    emptyOutDir: true,
    sourcemap: true,
    minify: 'esbuild',
    rollupOptions: {
      output: {
        // Split heavyweight vendor libraries out of the entry chunk so vendor
        // code caches independently of app code across redeploys. Function form
        // (not the object form) because some packages — e.g. y-protocols — are
        // imported only via subpaths and expose no root entry to name directly.
        manualChunks(id) {
          if (!id.includes('node_modules')) return undefined;
          if (/[\\/]node_modules[\\/](react|react-dom|scheduler)[\\/]/.test(id)) return 'react';
          if (id.includes('@xyflow')) return 'flow';
          if (id.includes('elkjs')) return 'layout';
          if (/[\\/]node_modules[\\/](yjs|y-protocols|y-indexeddb|lib0)[\\/]/.test(id)) {
            return 'collab';
          }
          return undefined;
        },
      },
    },
  },
});
