#!/usr/bin/env tsx
/**
 * Generate `docs/DIAGNOSTIC-CODES.md` from `src/text/langium/diagnostic-codes.ts`.
 *
 * The table in the source is the single source of truth; this script renders it
 * for humans and agents. `test/unit/diagnostic-codes.test.ts` fails if the
 * committed document drifts from the table, so regenerating is not optional
 * after adding a code.
 *
 * Run: npm run codes
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DIAGNOSTIC_CODES } from '../src/text/langium/diagnostic-codes';

const FAMILIES: Array<{ prefix: string; title: string; blurb: string }> = [
  { prefix: 'lexer/', title: 'Lexical', blurb: 'The text could not be turned into tokens. Always an error; the file cannot be read as SysML until it is fixed.' },
  { prefix: 'parse/', title: 'Syntactic', blurb: 'The tokens do not form a legal declaration. `expected` lists what would have been legal at that position and `found` is what was actually written.' },
  { prefix: 'ref/', title: 'Reference resolution', blurb: 'A name did not resolve. These are WARNINGS: the textual name is preserved in the model, so the file still loads, but nothing is bound to it.' },
  { prefix: 'validation/', title: 'Model validation', blurb: 'The file parsed, but the model it describes breaks a rule. Each code matches a rule id in `src/validation/rules.ts`.' },
  { prefix: 'import/', title: 'Input handling', blurb: 'Problems with the input itself rather than its content: wrong format, encoding normalisation, or a failure inside the checker.' },
  { prefix: 'roundtrip/', title: 'Round-trip', blurb: 'Guards against the tool producing notation it cannot read back.' },
];

const rows = (prefix: string): string =>
  DIAGNOSTIC_CODES.filter((c) => c.code.startsWith(prefix))
    .map((c) => `### \`${c.code}\`\n\n- **Severity:** ${c.severity}\n- **Source:** ${c.source}\n- **Fires when:** ${c.when}\n- **Hint given:** ${c.hint}\n`)
    .join('\n');

const doc = `<!-- GENERATED by scripts/gen-diagnostic-codes.ts — do not edit by hand.
     Edit src/text/langium/diagnostic-codes.ts and run \`npm run codes\`. -->

# Diagnostic codes

Every finding Sysprose reports about a \`.sysml\` source file carries a **code**
from this catalogue. Codes are stable: messages get reworded, codes do not, so
automation should branch on \`code\` and never on \`message\`.

This is the reference half of the **Agent Diagnostics Contract**; the workflow
that uses it is in [\`AGENT-TEXT-CAMPAIGN.md\`](AGENT-TEXT-CAMPAIGN.md).

## The shape of a finding

\`\`\`jsonc
{
  "id": "parse#0",
  "code": "parse/mismatched-token",   // stable catalogue id — branch on this
  "severity": "error",                 // error | warning | info
  "source": "parser",                  // lexer | parser | mapper | validation | import
  "message": "Expecting token of type '}' but found \`def\`.",
  "range": {                           // 1-based line/column, 0-based offset
    "start": { "line": 2, "column": 10, "offset": 25 },
    "end":   { "line": 2, "column": 13, "offset": 28 }
  },
  "expected": ["}"],                   // parser errors: what would have been legal
  "found": "def",                      // what was written instead
  "hint": "Expected \`}\` here, found \`def\`. …",
  "elementId": "…",                    // validation findings: the offending element
  "elementName": "Vehicle"
}
\`\`\`

\`range\` is present on every finding derived from the source text. \`elementId\`
and \`elementName\` appear on validation findings. \`expected\`/\`found\` appear on
lexer and parser errors.

## Severity means

| Severity | Meaning | Does the file load? |
|---|---|---|
| \`error\` | The file is wrong and must be fixed. | Partially — error recovery keeps what it can. |
| \`warning\` | The file loads, but something in it is unresolved or questionable. | Yes. |
| \`info\` | Something was normalised on the way in. | Yes. |

${FAMILIES.map((f) => `## ${f.title}\n\n${f.blurb}\n\n${rows(f.prefix)}`).join('\n')}
---

*${DIAGNOSTIC_CODES.length} codes. Generated from \`src/text/langium/diagnostic-codes.ts\`.*
`;

const out = resolve(process.cwd(), 'docs/DIAGNOSTIC-CODES.md');
writeFileSync(out, doc);
process.stdout.write(`Wrote ${out} — ${DIAGNOSTIC_CODES.length} codes.\n`);
