#!/usr/bin/env tsx
/**
 * Generate `docs/CLI-REFERENCE.md` from `scripts/lib/sysprose-spec.ts`.
 *
 * The command table in that module is the single source of truth: the
 * dispatcher parses it, `--help` renders it, and this script renders it for a
 * reader who has not run the command yet. `test/unit/cli-reference.test.ts`
 * fails when the committed document differs from what this renders, so
 * regenerating is not optional after adding a subcommand or a flag — which is
 * the point. A flag that exists and is undocumented, and a documented flag that
 * no longer exists, are the two ways a command and its reference stop
 * describing the same tool, and neither can survive a green suite here.
 *
 * The renderer is exported and the write is guarded by an is-this-the-entry-
 * point check: the drift test imports {@link renderCliReference} to compare it
 * against the file on disk, and an import that quietly rewrote that file would
 * make the test pass by destroying the evidence.
 *
 * Run: npm run commands
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { FlagSpec } from './lib/args';
import {
  CHECK_EXIT_CODES,
  COMMANDS,
  COMMON_FLAGS,
  EXIT_CODES,
  TRACE_PRESETS,
  type CommandSpec,
} from './lib/sysprose-spec';

/**
 * One Markdown table cell.
 *
 * A `doc` line written for a terminal is not safe in a table: `--relation`'s
 * lists its presets separated by `|`, which ends the cell, and `--json`'s
 * describes the payload as `{ok, file, <report>}`, whose `<report>` a Markdown
 * renderer reads as an HTML tag and drops. Both are the spec's words and must
 * reach the page as written.
 */
function cell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** `--flag VALUE` as the reference writes it, in code ticks. */
function flagName(f: FlagSpec): string {
  const alias = f.short ? `\`-${f.short}\`, ` : '';
  return `${alias}\`--${f.name}${f.kind === 'value' ? ` ${f.metavar ?? 'VALUE'}` : ''}\``;
}

/** One row per flag: how it is written, what it does, what it does otherwise. */
function flagTable(flags: readonly FlagSpec[]): string {
  return [
    '| Flag | What it does | Default |',
    '|---|---|---|',
    ...flags.map(
      (f) => `| ${flagName(f)} | ${cell(f.doc)} | ${f.fallback ? `\`${f.fallback}\`` : '—'} |`,
    ),
  ].join('\n');
}

/** One subcommand: the question it answers, how to run it, and its flags. */
function commandSection(cmd: CommandSpec): string {
  const own = cmd.flags.length > 0 ? flagTable(cmd.flags) : '_No flags of its own._';
  return [
    `### \`${cmd.name}\``,
    '',
    `**${cmd.question}**`,
    '',
    '```bash',
    `npm run sysprose -- ${cmd.name} <file.sysml|-> [options]`,
    '```',
    '',
    own,
    '',
    `Computed by \`${cmd.backedBy}\`. With \`--json\` the answer is published under \`${cmd.payloadKey}\`, beside \`ok\` and \`file\`.`,
  ].join('\n');
}

/** The whole document, as a string, from the spec and nothing else. */
export function renderCliReference(): string {
  const presets = [...TRACE_PRESETS.entries()]
    .map(([name, kinds]) => `| \`${name}\` | ${kinds.map((k) => `\`${k}\``).join(', ')} |`)
    .join('\n');

  return `<!-- GENERATED by scripts/gen-cli-reference.ts — do not edit by hand.
     Edit scripts/lib/sysprose-spec.ts and run \`npm run commands\`. -->

# Command reference

Two commands read a \`.sysml\` file from a terminal. [\`npm run check\`](#npm-run-check)
says whether the file is **sound**; \`npm run sysprose\` says what is **in** it.
Each subcommand is a thin shell over the exported function named in its
\`Backed by\` line, so a figure read here and the same figure computed from that
import cannot differ. The app answers the same QUESTIONS, but several of its
views draw their own projection rather than call the reporting function — the
[user guide](USER-GUIDE.md) and the README's capability table mark which, and
say how the two can differ.

For what the answers mean — and for the app the commands mirror — read the
[user guide](USER-GUIDE.md). For what a diagnostic \`code\` means, read the
[diagnostic-code catalogue](DIAGNOSTIC-CODES.md).

## \`npm run sysprose\`

\`\`\`bash
npm run sysprose -- <subcommand> <file.sysml|-> [options]
cat model.sysml | npm run sysprose -- stats -
npm run sysprose -- --help                 # the subcommand list
npm run sysprose -- <subcommand> --help    # the flags of one subcommand
\`\`\`

${EXIT_CODES.replace('Exit codes: ', '**Exit codes.** ')}.

Exit **1** is about the *model*, not the report: these subcommands report and do
not judge, so finding four unused definitions is an answer and exits 0. A model
that did not load cleanly still produces a report — of what error recovery
salvaged — with a \`degraded\` banner on stderr saying so.

**stdout carries the report; stderr carries everything about the file**, for
every exit code, so a pipeline gets the data and a person gets the warnings.

Two refusals, each replacing an answer that would read as true: a file that
parsed and produced no elements exits 2 rather than reporting an empty success,
and an element reference matching several elements exits 2 with the candidates
rather than reporting on the first one.

### The subcommands

| Subcommand | Question it answers | \`--json\` key |
|---|---|---|
${COMMANDS.map((c) => `| [\`${c.name}\`](#${c.name}) | ${cell(c.question)} | \`${c.payloadKey}\` |`).join('\n')}

### Options every subcommand takes

${flagTable(COMMON_FLAGS)}

**\`--no-library\` and \`--include-library\` are two different knobs.**
\`--no-library\` skips *binding*: it changes the model, and library types then
report as unresolved. \`--include-library\` changes *reporting*: the library is
bound and then listed alongside your model. Only \`elements\` can honour the
second one — every other report excludes the library by construction and states
its own excluded count — so it is refused elsewhere rather than accepted and
quietly ignored.

## Subcommands in detail

${COMMANDS.map(commandSection).join('\n\n')}

### \`trace\` relationship presets

A preset names the **relationship** kinds only. The row and column metaclasses
are read off the model's own edges, because \`satisfy\` links a \`PartUsage\` to a
\`RequirementDefinition\` in one model and to a \`RequirementUsage\` in the next,
and a matrix that silently reports zero rows for the second shape is worse than
no command at all. \`--from\` / \`--to\` override the derived axes; an override
naming a metaclass the model has none of is refused rather than honoured into an
empty matrix.

| \`--relation\` | Relationship metaclasses tabulated |
|---|---|
${presets}

## \`npm run check\`

\`\`\`bash
npm run check -- <file.sysml> [more files…] [options]
cat model.sysml | npm run check -- -
\`\`\`

| Flag | What it does |
|---|---|
| \`--json\` | Machine-readable report on stdout: \`{ok, files: [...]}\` — \`files\`, plural, because \`check\` takes several |
| \`--strict\` | Treat warnings as failures (affects \`ok\` and the exit code) |
| \`--no-library\` | Skip standard-library binding (faster; library types such as \`Real\` then report as unresolved) |
| \`--ranges\` | Include the element→source-range table |
| \`-h\`, \`--help\` | This text |

**${CHECK_EXIT_CODES}** — and this is NOT \`sysprose\`'s contract. \`check\`
*judges*: a file that parsed perfectly and broke one validation rule loaded
cleanly and still exits 1. \`sysprose\` *reports*, so its exit 1 is about the
model, not the findings.

Parses each file, binds the bundled standard library, and runs the validation
rules; \`-\` reads stdin, as with \`sysprose\`. Every finding
carries a stable \`code\`, a source \`range\` (line, column and offset, start and
end) and a one-line \`hint\`; parser errors also carry \`expected\` and \`found\`.
Branch on \`code\`, never on \`message\` — see
[\`DIAGNOSTIC-CODES.md\`](DIAGNOSTIC-CODES.md).

---

*${COMMANDS.length} subcommands. Generated from \`scripts/lib/sysprose-spec.ts\`.*
`;
}

/**
 * Only write when this file was RUN. Imported — which the drift test does — it
 * must not touch the document it is being compared against.
 */
const runAsScript =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (runAsScript) {
  const out = resolve(process.cwd(), 'docs/CLI-REFERENCE.md');
  writeFileSync(out, renderCliReference());
  process.stdout.write(`Wrote ${out} — ${COMMANDS.length} subcommands.\n`);
}
