/**
 * Auto-generate `docs/TEST-SUMMARY.md` from a real `vitest run`.
 *
 * `docs/TEST-REPORT.md` is the hand-authored, narrative feature-coverage report
 * (traceability matrix, verdicts). This script does NOT regenerate that — it
 * produces the *machine-checkable* companion: exact per-file pass/fail/skip
 * counts from an actual run, so the narrative numbers can be reconciled against
 * ground truth (previously `npm run report` pointed at a script that did not
 * exist, so the counts silently drifted).
 *
 * Run:  npm run report
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const out = path.join(root, 'docs', 'TEST-SUMMARY.md');

interface VitestJson {
  numTotalTests: number;
  numPassedTests: number;
  numFailedTests: number;
  numPendingTests: number;
  numTotalTestSuites: number;
  testResults: Array<{
    name: string;
    assertionResults: Array<{ status: string }>;
  }>;
}

function run(): VitestJson {
  const raw = execFileSync(
    'npx',
    ['vitest', 'run', '--reporter=json'],
    { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  );
  // The JSON object is the last well-formed `{...}` block on stdout.
  const start = raw.indexOf('{');
  return JSON.parse(raw.slice(start)) as VitestJson;
}

function main(): void {
  const r = run();
  const rows = r.testResults
    .map((f) => {
      const rel = path.relative(root, f.name);
      const passed = f.assertionResults.filter((a) => a.status === 'passed').length;
      const failed = f.assertionResults.filter((a) => a.status === 'failed').length;
      const skipped = f.assertionResults.filter(
        (a) => a.status === 'pending' || a.status === 'skipped',
      ).length;
      return { rel, passed, failed, skipped };
    })
    .sort((a, b) => a.rel.localeCompare(b.rel));

  const lines = [
    '# Test Summary (auto-generated)',
    '',
    '> Generated by `npm run report` (`scripts/gen-test-report.ts`) from a real',
    "> `vitest run`. This is the machine-checkable companion to the hand-authored",
    '> `docs/TEST-REPORT.md`; if the numbers disagree, this file is ground truth.',
    '',
    `- **Files:** ${r.numTotalTestSuites}`,
    `- **Tests:** ${r.numTotalTests} total — ` +
      `${r.numPassedTests} passed, ${r.numFailedTests} failed, ${r.numPendingTests} skipped`,
    '',
    '| File | Passed | Failed | Skipped |',
    '|------|-------:|-------:|--------:|',
    ...rows.map((x) => `| ${x.rel} | ${x.passed} | ${x.failed} | ${x.skipped} |`),
    '',
  ];
  writeFileSync(out, lines.join('\n'));
   
  console.log(`Wrote ${path.relative(root, out)} — ${r.numTotalTests} tests, ${r.numFailedTests} failed.`);
}

main();
