/**
 * The command table and its documentation must not drift.
 *
 * `docs/CLI-REFERENCE.md` is what a person reads before they run `npm run
 * sysprose` for the first time, and what an agent reads to find out which
 * subcommand answers its question. The dispatcher, `--help` and that document
 * are three renderings of ONE table (`scripts/lib/sysprose-spec.ts`), so the
 * only way they can disagree is if the committed document was not regenerated.
 * This is the same guard `test/unit/diagnostic-codes.test.ts` puts on the
 * diagnostic catalogue, and it fails the same way: with the command to run.
 *
 * The whole-document comparison is deliberate rather than a set of spot checks.
 * A flag whose `doc` line was reworded is a flag whose documentation is now
 * wrong, and no assertion over names alone would notice.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DEFAULT_MAX_CORE as SEMANTICS_MAX_CORE, STATEMENT_KINDS } from '@semantics/index';
import { renderCliReference } from '../../scripts/gen-cli-reference';
import {
  CHECK_EXIT_CODES,
  COMMANDS,
  COMMON_FLAGS,
  DEFAULT_MAX_CORE,
  EXIT_CODES,
  STATEMENT_KIND_FLAG_VALUES,
  VERIFY_EXIT_CODES,
  WRITE_EXIT_CODES,
  flagsFor,
} from '../../scripts/lib/sysprose-spec';

const PATH = resolve(process.cwd(), 'docs/CLI-REFERENCE.md');
const DOC = readFileSync(PATH, 'utf8');

describe('the generated command reference', () => {
  it('is what the generator renders today', () => {
    expect(
      DOC,
      'docs/CLI-REFERENCE.md is stale — run `npm run commands`',
    ).toBe(renderCliReference());
  });

  it('says it is generated, and by what', () => {
    expect(DOC.startsWith('<!-- GENERATED by scripts/gen-cli-reference.ts')).toBe(true);
    expect(DOC).toContain('npm run commands');
  });

  it('gives every subcommand a section of its own', () => {
    const documented = new Set([...DOC.matchAll(/^### `([a-z-]+)`$/gm)].map((m) => m[1]));
    const missing = COMMANDS.map((c) => c.name).filter((n) => !documented.has(n));
    expect(missing, `subcommands with no section — run \`npm run commands\`:\n${missing.join('\n')}`)
      .toEqual([]);
  });

  it('documents every flag every subcommand accepts', () => {
    const missing: string[] = [];
    for (const cmd of COMMANDS) {
      for (const f of flagsFor(cmd)) {
        // A shared flag is documented once, in the common table; an own flag is
        // documented in the subcommand's own table. Either way the reader of a
        // subcommand can find it, which is what has to stay true.
        if (!DOC.includes(`\`--${f.name}`)) missing.push(`${cmd.name} --${f.name}`);
      }
    }
    expect(missing, `undocumented flags:\n${missing.join('\n')}`).toEqual([]);
  });

  it("states the question each subcommand answers, in the spec's own words", () => {
    // Undo the table-cell escaping first: a `doc` line reaches the page as
    // written, but `|` and `<…>` have to be escaped to survive Markdown, and
    // comparing against the escaped form would be comparing against the
    // renderer rather than against the spec.
    const plain = DOC.replace(/\\\|/g, '|').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
    for (const cmd of COMMANDS) expect(plain, `${cmd.name}'s question`).toContain(cmd.question);
    for (const f of COMMON_FLAGS) expect(plain, `--${f.name}'s doc line`).toContain(f.doc);
  });

  it('states the exit-code contract', () => {
    expect(DOC).toContain('0 clean');
    expect(DOC).toContain('2 usage/IO error');
  });

  /**
   * The third contract, guarded where it can actually go wrong: PER SECTION.
   *
   * This document used to state the exit codes once for the whole `sysprose`
   * section, which was true while every subcommand reported. `verify` judges,
   * and under that one paragraph its exit **1** would have been documented as
   * "the model did not load cleanly" — the exact opposite of *refuted*. A
   * document-wide `toContain` would not have noticed: `VERIFY_EXIT_CODES`
   * appearing SOMEWHERE says nothing about it appearing in the right place, or
   * about the reporting sections not carrying it too. So each section is sliced
   * out and checked against the contract its own row declares, both ways.
   */
  it('quotes each subcommand’s own exit contract in its own section, and no other', () => {
    const sections = new Map<string, string>();
    const heads = [...DOC.matchAll(/^### `([a-z-]+)`$/gm)];
    for (const [i, m] of heads.entries()) {
      const start = m.index!;
      const end = i + 1 < heads.length ? heads[i + 1].index! : DOC.length;
      sections.set(m[1], DOC.slice(start, end));
    }
    // All three contracts must actually be in play, or every assertion below
    // holds trivially over a table that lost one of them.
    const CONTRACTS = { report: EXIT_CODES, verify: VERIFY_EXIT_CODES, write: WRITE_EXIT_CODES };
    expect(
      COMMANDS.map((c) => c.exitContract).filter((v, i, a) => a.indexOf(v) === i).sort(),
      'the command table no longer declares all three exit contracts',
    ).toEqual(['report', 'verify', 'write']);

    for (const cmd of COMMANDS) {
      const section = sections.get(cmd.name);
      expect(section, `no section for \`${cmd.name}\``).toBeDefined();
      const body = (s: string) => s.replace('Exit codes: ', '');
      for (const [name, contract] of Object.entries(CONTRACTS)) {
        const isOwn = name === cmd.exitContract;
        expect(
          section!.includes(body(contract)),
          isOwn
            ? `\`${cmd.name}\` declares exitContract '${cmd.exitContract}' but its section does not quote that contract — run \`npm run commands\``
            : `\`${cmd.name}\`'s section quotes the '${name}' exit contract, which is not its own`,
        ).toBe(isOwn);
      }
    }
  });

  it('gives the two writing subcommands a contract with no exit 1 in it', () => {
    // `evidence-attach` and `evidence-detach` refuse a degraded model outright
    // — `refuseDegradedWrite` is the opening statement of both — so the
    // reporting contract's 1, "the model did not load cleanly (the report is of
    // what parsed)", names a state they cannot reach. Documenting them under it
    // promised a partial answer that will never come.
    expect(WRITE_EXIT_CODES).not.toContain('· 1 ');
    expect(WRITE_EXIT_CODES).toContain('a degraded model is refused');
    expect(WRITE_EXIT_CODES).not.toBe(EXIT_CODES);
    expect(
      COMMANDS.filter((c) => c.exitContract === 'write').map((c) => c.name).sort(),
      'the writing contract is declared by exactly the two subcommands that write the file back',
    ).toEqual(['evidence-attach', 'evidence-detach']);
  });

  it('states in words that `verify`’s 1 means refuted, not a load failure', () => {
    // The two contracts are opposites at 1, and that is the sentence a reader
    // acts on. It is asserted against the constant rather than retyped.
    expect(VERIFY_EXIT_CODES).toContain('1 at least one obligation refuted');
    expect(EXIT_CODES).toContain('1 the model did not load cleanly');
    expect(VERIFY_EXIT_CODES).not.toBe(EXIT_CODES);
    expect(VERIFY_EXIT_CODES).not.toBe(CHECK_EXIT_CODES);
  });
});

/**
 * The one value list the command table copies rather than imports.
 *
 * `scripts/lib/sysprose-spec.ts` is imported by the documentation generator and
 * by three doc guards, and it is kept free of model imports so none of them
 * pulls the core graph in to render a help line. The price is a hand-copied
 * vocabulary, and a vocabulary in two places is a vocabulary that drifts: a
 * fourth statement kind added to `@semantics/statement-kind` would be a kind
 * `--kind` silently refuses, with the reference documenting three and the
 * dispatcher accepting three. This is the assertion that makes the copy safe.
 */
describe('the `--kind` flag and the statement-kind vocabulary', () => {
  it('offers exactly the kinds the semantics module declares, in the same order', () => {
    expect(
      STATEMENT_KIND_FLAG_VALUES,
      '`requirements --kind` and `STATEMENT_KINDS` disagree about what a statement kind is',
    ).toEqual([...STATEMENT_KINDS]);
  });

  it('names every one of them in the reference', () => {
    const kindFlag = COMMANDS.flatMap((c) => c.flags).find((f) => f.name === 'kind');
    expect(kindFlag, '`requirements` no longer declares `--kind`').toBeDefined();
    // The flag's ROW, not the whole document. `toContain` over `DOC` passes on
    // any of the three by accident — `prose` is inside the word `sysprose`,
    // `prompt` inside the `prompts` section, `requirement` inside the
    // `requirements` one — so deleting this row outright would not have failed
    // it. A vocabulary guard that cannot see its own subject is not a guard.
    const row = DOC.split('\n').find((l) => l.startsWith('| `--kind KIND` |'));
    expect(row, 'the reference no longer renders a `--kind` row').toBeDefined();
    for (const kind of STATEMENT_KINDS) {
      expect(kindFlag!.doc, `--kind's doc line offers ${kind}`).toContain(kind);
      expect(row!, `the reference's --kind row names ${kind}`).toContain(kind);
    }
  });
});

/**
 * The other value the command table copies rather than imports.
 *
 * Same reason as `--kind`'s vocabulary above, same failure if it drifts:
 * `--max-core`'s help line and the generated reference would promise a budget
 * the engine does not use, and a reader who trusted the printed default would
 * mis-read every core that came back unreduced.
 */
describe('the `--max-core` default and the engine that honours it', () => {
  it('is the number `src/semantics/consistency.ts` actually defaults to', () => {
    expect(
      DEFAULT_MAX_CORE,
      '`--max-core`\u2019s documented default and `DEFAULT_MAX_CORE` disagree',
    ).toBe(SEMANTICS_MAX_CORE);
  });

  it('names it in the reference', () => {
    const row = DOC.split('\n').find((l) => l.startsWith('| `--max-core N` |'));
    expect(row, 'the reference no longer renders a `--max-core` row').toBeDefined();
    expect(row!, 'the --max-core row no longer prints its default').toContain(
      `${DEFAULT_MAX_CORE} members`,
    );
  });
});

/**
 * The `npm run check` section is the half of this document no spec renders.
 *
 * Everything above comes from `sysprose-spec.ts`, so the whole-document
 * comparison guards it. The check section was hand-written prose inside the
 * generator's template literal, which made that comparison tautological: it
 * compared the same sentence against itself, and the sentence was wrong — it
 * claimed `check` shared `sysprose`'s exit-code contract, when `check` exits 1
 * on a file that loaded perfectly and broke a validation rule. So the section is
 * checked against its SUBJECT instead: `scripts/sysml-check.ts`'s own `--help`.
 *
 * That file cannot be imported — it calls `runMain` at module scope, so an
 * import would run the command — so its `USAGE` template literal is read out of
 * the source text. Reading source text is the price of not executing a script,
 * and it is what makes a flag added to `check` fail here.
 */
describe("the reference's `npm run check` section and the command's own --help", () => {
  const CHECK_SRC = readFileSync(resolve(process.cwd(), 'scripts/sysml-check.ts'), 'utf8');
  const USAGE = /const USAGE = `([\s\S]*?)`;/.exec(CHECK_SRC)![1];
  const SECTION = DOC.slice(DOC.indexOf('## `npm run check`'));

  it('reads its usage out of the command, not out of prose', () => {
    expect(USAGE, 'scripts/sysml-check.ts no longer declares a USAGE literal').toContain(
      'npm run check',
    );
    expect(SECTION.length, 'docs/CLI-REFERENCE.md has no `npm run check` section').toBeGreaterThan(
      0,
    );
  });

  it('shows every synopsis line the command shows', () => {
    // Including the multi-file form: the project's own gate checks two files at
    // once, and a reference that shows one file teaches a reader to loop.
    const synopses = USAGE.split('\n')
      .map((l) => l.trim())
      .filter((l) => l.includes('npm run check --'));
    expect(synopses.length, 'USAGE shows no `npm run check` invocation').toBeGreaterThan(0);
    for (const line of synopses) expect(SECTION, `the reference shows: ${line}`).toContain(line);
  });

  it('documents every flag the command documents', () => {
    const flags = [...new Set([...USAGE.matchAll(/(?:^|\s)(--?[a-z][a-z-]*)/g)].map((m) => m[1]))]
      // `--strict`'s own doc line mentions itself; the set is what matters.
      .filter((f) => f !== '--');
    expect(flags.length, 'USAGE lists no flags').toBeGreaterThan(3);
    const missing = flags.filter((f) => !SECTION.includes(`\`${f}\``));
    expect(
      missing,
      `flags \`npm run check\` documents that the reference does not:\n${missing.join('\n')}`,
    ).toEqual([]);
  });

  it("states check's exit-code contract, in the command's own words", () => {
    expect(SECTION, 'the section quotes CHECK_EXIT_CODES').toContain(CHECK_EXIT_CODES);
    // USAGE is read as SOURCE, so what it holds is the interpolation, not the
    // value — which is the thing being asserted: the help text renders this
    // constant rather than a second copy of the sentence.
    expect(USAGE, "the command's --help interpolates the same constant").toContain(
      // Spelled in pieces so the lint rule that hunts for an accidental
      // template placeholder in a plain string does not read it as one.
      `\${${'CHECK_EXIT_CODES'}}`,
    );
    // The distinction is the whole point of stating it twice: `sysprose`'s 1 is
    // about the model, `check`'s is about the findings. A future edit that
    // collapses them back into "same exit-code contract" fails here.
    expect(SECTION).not.toContain('Same exit-code contract');
    expect(CHECK_EXIT_CODES).not.toBe(EXIT_CODES);
  });
});
