/**
 * The command table and its documentation must not drift.
 *
 * `docs/CLI-REFERENCE.md` is what a person reads before they run `npm run
 * sysprose` for the first time, and what an agent reads to find out which
 * subcommand answers its question. The dispatcher, `--help` and that document
 * are three renderings of ONE table (`scripts/lib/sysprose-spec.ts`), so the
 * only way they can disagree is if the committed document was not regenerated.
 * This is the same guard `test/unit/diagnostic-codes.test.ts` puts on the
 * diagnostic catalogue, and it fails the same way: with the command to run.
 *
 * The whole-document comparison is deliberate rather than a set of spot checks.
 * A flag whose `doc` line was reworded is a flag whose documentation is now
 * wrong, and no assertion over names alone would notice.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DEFAULT_MAX_CORE as SEMANTICS_MAX_CORE, STATEMENT_KINDS } from '@semantics/index';
import { DEFAULT_MAX_CONFIGS as ENGINE_MAX_CONFIGS, PATTERNS, SCOPES } from '@api/index';
import { renderCliReference } from '../../scripts/gen-cli-reference';
import {
  BEHAVIOUR_EXIT_CODES,
  CHECK_EXIT_CODES,
  COMMANDS,
  COMMON_FLAGS,
  DEFAULT_MAX_CONFIGS,
  DEFAULT_MAX_CORE,
  EXIT_CODES,
  PATTERN_NAMES,
  REFINE_EXIT_CODES,
  SCOPE_NAMES,
  STATEMENT_KIND_FLAG_VALUES,
  VERIFY_EXIT_CODES,
  WRITE_EXIT_CODES,
  exitCodesFor,
  flagsFor,
  renderTopUsage,
} from '../../scripts/lib/sysprose-spec';

const PATH = resolve(process.cwd(), 'docs/CLI-REFERENCE.md');
const DOC = readFileSync(PATH, 'utf8');

describe('the generated command reference', () => {
  it('is what the generator renders today', () => {
    expect(
      DOC,
      'docs/CLI-REFERENCE.md is stale — run `npm run commands`',
    ).toBe(renderCliReference());
  });

  it('says it is generated, and by what', () => {
    expect(DOC.startsWith('<!-- GENERATED by scripts/gen-cli-reference.ts')).toBe(true);
    expect(DOC).toContain('npm run commands');
  });

  it('gives every subcommand a section of its own', () => {
    const documented = new Set([...DOC.matchAll(/^### `([a-z-]+)`$/gm)].map((m) => m[1]));
    const missing = COMMANDS.map((c) => c.name).filter((n) => !documented.has(n));
    expect(missing, `subcommands with no section — run \`npm run commands\`:\n${missing.join('\n')}`)
      .toEqual([]);
  });

  it('documents every flag every subcommand accepts', () => {
    const missing: string[] = [];
    for (const cmd of COMMANDS) {
      for (const f of flagsFor(cmd)) {
        // A shared flag is documented once, in the common table; an own flag is
        // documented in the subcommand's own table. Either way the reader of a
        // subcommand can find it, which is what has to stay true.
        if (!DOC.includes(`\`--${f.name}`)) missing.push(`${cmd.name} --${f.name}`);
      }
    }
    expect(missing, `undocumented flags:\n${missing.join('\n')}`).toEqual([]);
  });

  it("states the question each subcommand answers, in the spec's own words", () => {
    // Undo the table-cell escaping first: a `doc` line reaches the page as
    // written, but `|` and `<…>` have to be escaped to survive Markdown, and
    // comparing against the escaped form would be comparing against the
    // renderer rather than against the spec.
    const plain = DOC.replace(/\\\|/g, '|').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
    for (const cmd of COMMANDS) expect(plain, `${cmd.name}'s question`).toContain(cmd.question);
    for (const f of COMMON_FLAGS) expect(plain, `--${f.name}'s doc line`).toContain(f.doc);
  });

  it('states the exit-code contract', () => {
    expect(DOC).toContain('0 clean');
    expect(DOC).toContain('2 usage/IO error');
  });

  /**
   * The third contract, guarded where it can actually go wrong: PER SECTION.
   *
   * This document used to state the exit codes once for the whole `sysprose`
   * section, which was true while every subcommand reported. `verify` judges,
   * and under that one paragraph its exit **1** would have been documented as
   * "the model did not load cleanly" — the exact opposite of *refuted*. A
   * document-wide `toContain` would not have noticed: `VERIFY_EXIT_CODES`
   * appearing SOMEWHERE says nothing about it appearing in the right place, or
   * about the reporting sections not carrying it too. So each section is sliced
   * out and checked against the contract its own row declares, both ways.
   */
  it('quotes each subcommand’s own exit contract in its own section, and no other', () => {
    const sections = new Map<string, string>();
    const heads = [...DOC.matchAll(/^### `([a-z-]+)`$/gm)];
    for (const [i, m] of heads.entries()) {
      const start = m.index!;
      const end = i + 1 < heads.length ? heads[i + 1].index! : DOC.length;
      sections.set(m[1], DOC.slice(start, end));
    }
    // All three contracts must actually be in play, or every assertion below
    // holds trivially over a table that lost one of them.
    const CONTRACTS = {
      report: EXIT_CODES,
      verify: VERIFY_EXIT_CODES,
      refine: REFINE_EXIT_CODES,
      write: WRITE_EXIT_CODES,
      behaviour: BEHAVIOUR_EXIT_CODES,
    };
    expect(
      COMMANDS.map((c) => c.exitContract).filter((v, i, a) => a.indexOf(v) === i).sort(),
      'the command table no longer declares all five exit contracts',
    ).toEqual(['behaviour', 'refine', 'report', 'verify', 'write']);

    for (const cmd of COMMANDS) {
      const section = sections.get(cmd.name);
      expect(section, `no section for \`${cmd.name}\``).toBeDefined();
      const body = (s: string) => s.replace('Exit codes: ', '');
      for (const [name, contract] of Object.entries(CONTRACTS)) {
        const isOwn = name === cmd.exitContract;
        expect(
          section!.includes(body(contract)),
          isOwn
            ? `\`${cmd.name}\` declares exitContract '${cmd.exitContract}' but its section does not quote that contract — run \`npm run commands\``
            : `\`${cmd.name}\`'s section quotes the '${name}' exit contract, which is not its own`,
        ).toBe(isOwn);
      }
    }
  });

  it('gives the two writing subcommands a contract with no exit 1 in it', () => {
    // `evidence-attach` and `evidence-detach` refuse a degraded model outright
    // — `refuseDegradedWrite` is the opening statement of both — so the
    // reporting contract's 1, "the model did not load cleanly (the report is of
    // what parsed)", names a state they cannot reach. Documenting them under it
    // promised a partial answer that will never come.
    expect(WRITE_EXIT_CODES).not.toContain('· 1 ');
    expect(WRITE_EXIT_CODES).toContain('a degraded model is refused');
    expect(WRITE_EXIT_CODES).not.toBe(EXIT_CODES);
    expect(
      COMMANDS.filter((c) => c.exitContract === 'write').map((c) => c.name).sort(),
      'the writing contract is declared by exactly the two subcommands that write the file back',
    ).toEqual(['evidence-attach', 'evidence-detach']);
  });

  it('gives `refine` a contract with no feature values and no --free in it', () => {
    // `verify` and `consistency` judge the file's VALUES; `refine` judges an
    // ARCHITECTURE. Under `verify`'s paragraph the `refine` section published
    // three promises the command cannot keep — "with every feature at its model
    // value", "a relation not evaluable at the model's values", and a `--free`
    // clause for a flag it does not have — in its own `--help` and in this
    // document. The two contracts still agree about what 1 MEANS.
    expect(REFINE_EXIT_CODES).toContain('1 at least one obligation refuted');
    expect(REFINE_EXIT_CODES).not.toContain('at its model value');
    expect(REFINE_EXIT_CODES).not.toContain('--free,');
    expect(REFINE_EXIT_CODES).toContain('there is no --free here');
    // The two undecided states this lane must never launder are named in it.
    expect(REFINE_EXIT_CODES).toContain('vacuous');
    expect(REFINE_EXIT_CODES).toContain('absent solver');
    expect(REFINE_EXIT_CODES).not.toBe(VERIFY_EXIT_CODES);
    const refining = COMMANDS.filter((c) => c.exitContract === 'refine').map((c) => c.name);
    expect(refining, 'the refinement contract is declared by exactly `refine`').toEqual(['refine']);
    // And no `--free` flag exists on the row that publishes that sentence.
    expect(flagsFor(COMMANDS.find((c) => c.name === 'refine')!).map((f) => f.name)).not.toContain('free');
  });

  it('gives `check-behaviour` a contract with no solver and no --free in it', () => {
    // The same reason `refine` has its own, and the same failure if it did not:
    // under `verify`'s paragraph this command would publish an absent solver, a
    // `--timeout` and a `--free` it does not have — and §3.8 is explicit that
    // the engine is pure TypeScript, so "an absent solver" is a state it cannot
    // reach at all. The two contracts still agree about what 1 MEANS.
    expect(BEHAVIOUR_EXIT_CODES).toContain('1 at least one property refuted');
    expect(BEHAVIOUR_EXIT_CODES).toContain('witness trace');
    expect(BEHAVIOUR_EXIT_CODES).not.toContain('at its model value');
    expect(BEHAVIOUR_EXIT_CODES).toContain('There is no solver in this lane and no --free');
    // The undecided states this lane must never launder, named in it.
    expect(BEHAVIOUR_EXIT_CODES).toContain('vacuous');
    expect(BEHAVIOUR_EXIT_CODES).toContain('liveness');
    expect(BEHAVIOUR_EXIT_CODES).toContain('a bound the walk hit');
    expect(BEHAVIOUR_EXIT_CODES).not.toBe(VERIFY_EXIT_CODES);
    const behaving = COMMANDS.filter((c) => c.exitContract === 'behaviour').map((c) => c.name);
    expect(behaving, 'the behaviour contract is declared by exactly `check-behaviour`').toEqual([
      'check-behaviour',
    ]);
    // And no flag exists on that row for anything the sentence refuses.
    const flags = flagsFor(COMMANDS.find((c) => c.name === 'check-behaviour')!).map((f) => f.name);
    expect(flags).not.toContain('free');
    expect(flags).not.toContain('engine');
    expect(flags).not.toContain('timeout');
  });

  it('names every JUDGING subcommand in the top-level exit-code caveat', () => {
    // THE ONE PLACE A READER WHO HAS NOT RUN THE TOOL YET MEETS THE CONTRACT.
    // `sysprose --help` prints the REPORTING sentence — under which 1 means
    // "the model did not load cleanly" — and then names the subcommands that do
    // not obey it. `check-behaviour` was left out of that list while exiting 1
    // on a property refuted, so its exit 1 was documented as its own opposite.
    // Derived from the contracts rather than from a list of names, so a sixth
    // contract cannot be added and quietly left out the same way.
    const usage = renderTopUsage();
    expect(usage).toContain(EXIT_CODES);
    for (const cmd of COMMANDS) {
      const contract = exitCodesFor(cmd);
      // `report`'s 1 is about the load, and the writing commands have no 1.
      const judges = contract !== EXIT_CODES && contract !== WRITE_EXIT_CODES;
      expect(
        usage.includes(`\`${cmd.name}\` `) || usage.includes(`\`${cmd.name}\`,`),
        `${cmd.name} (${cmd.exitContract}) ${judges ? 'is judging and is not named' : 'reports and must not be named'} in the top-level caveat`,
      ).toBe(judges);
    }
    // And the sentence still reads as English with more than one of them in it.
    expect(usage).toContain('judge and have their own contract');
  });

  it('states in words that `verify`’s 1 means refuted, not a load failure', () => {
    // The two contracts are opposites at 1, and that is the sentence a reader
    // acts on. It is asserted against the constant rather than retyped.
    expect(VERIFY_EXIT_CODES).toContain('1 at least one obligation refuted');
    expect(EXIT_CODES).toContain('1 the model did not load cleanly');
    expect(VERIFY_EXIT_CODES).not.toBe(EXIT_CODES);
    expect(VERIFY_EXIT_CODES).not.toBe(CHECK_EXIT_CODES);
  });
});

/**
 * The one value list the command table copies rather than imports.
 *
 * `scripts/lib/sysprose-spec.ts` is imported by the documentation generator and
 * by three doc guards, and it is kept free of model imports so none of them
 * pulls the core graph in to render a help line. The price is a hand-copied
 * vocabulary, and a vocabulary in two places is a vocabulary that drifts: a
 * fourth statement kind added to `@semantics/statement-kind` would be a kind
 * `--kind` silently refuses, with the reference documenting three and the
 * dispatcher accepting three. This is the assertion that makes the copy safe.
 */
describe('the `--kind` flag and the statement-kind vocabulary', () => {
  it('offers exactly the kinds the semantics module declares, in the same order', () => {
    expect(
      STATEMENT_KIND_FLAG_VALUES,
      '`requirements --kind` and `STATEMENT_KINDS` disagree about what a statement kind is',
    ).toEqual([...STATEMENT_KINDS]);
  });

  it('names every one of them in the reference', () => {
    const kindFlag = COMMANDS.flatMap((c) => c.flags).find((f) => f.name === 'kind');
    expect(kindFlag, '`requirements` no longer declares `--kind`').toBeDefined();
    // The flag's ROW, not the whole document. `toContain` over `DOC` passes on
    // any of the three by accident — `prose` is inside the word `sysprose`,
    // `prompt` inside the `prompts` section, `requirement` inside the
    // `requirements` one — so deleting this row outright would not have failed
    // it. A vocabulary guard that cannot see its own subject is not a guard.
    const row = DOC.split('\n').find((l) => l.startsWith('| `--kind KIND` |'));
    expect(row, 'the reference no longer renders a `--kind` row').toBeDefined();
    for (const kind of STATEMENT_KINDS) {
      expect(kindFlag!.doc, `--kind's doc line offers ${kind}`).toContain(kind);
      expect(row!, `the reference's --kind row names ${kind}`).toContain(kind);
    }
  });
});

/**
 * The other value the command table copies rather than imports.
 *
 * Same reason as `--kind`'s vocabulary above, same failure if it drifts:
 * `--max-core`'s help line and the generated reference would promise a budget
 * the engine does not use, and a reader who trusted the printed default would
 * mis-read every core that came back unreduced.
 */
describe('the `--max-core` default and the engine that honours it', () => {
  it('is the number `src/semantics/consistency.ts` actually defaults to', () => {
    expect(
      DEFAULT_MAX_CORE,
      '`--max-core`\u2019s documented default and `DEFAULT_MAX_CORE` disagree',
    ).toBe(SEMANTICS_MAX_CORE);
  });

  it('names it in the reference', () => {
    const row = DOC.split('\n').find((l) => l.startsWith('| `--max-core N` |'));
    expect(row, 'the reference no longer renders a `--max-core` row').toBeDefined();
    expect(row!, 'the --max-core row no longer prints its default').toContain(
      `${DEFAULT_MAX_CORE} members`,
    );
  });
});

/**
 * The third and fourth values the command table copies rather than imports.
 *
 * `--pattern`'s help line offers a pattern catalogue and a scope list, and both
 * are spelled in `sysprose-spec.ts` for the same reason `--kind`'s vocabulary
 * is: that module is read by a documentation generator and three doc guards and
 * stays free of model imports. The failure a copy invites is precise — a
 * pattern added to `PATTERNS` and not offered here is one the reference does
 * not document, and one offered here and not in `PATTERNS` is a name
 * `check-behaviour` refuses with `verification/malformed-property` after telling
 * the reader to type it.
 */
describe('the `--pattern` vocabulary and the catalogue behind it', () => {
  it('offers exactly the patterns and scopes the engine declares, in the same order', () => {
    expect(
      PATTERN_NAMES,
      '`check-behaviour --pattern` and `PATTERNS` disagree about the catalogue',
    ).toEqual(PATTERNS.map((p) => p.name));
    expect(
      SCOPE_NAMES,
      '`check-behaviour --pattern` and `SCOPES` disagree about the scopes',
    ).toEqual(SCOPES.map((s) => s.name));
  });

  it('names every one of them in the reference, and says which two are liveness', () => {
    const row = DOC.split('\n').find((l) => l.startsWith('| `--pattern SPEC` |'));
    expect(row, 'the reference no longer renders a `--pattern` row').toBeDefined();
    for (const name of PATTERN_NAMES) expect(row!, `the row offers ${name}`).toContain(name);
    for (const name of SCOPE_NAMES) expect(row!, `the row offers ${name}`).toContain(name);
    // The half of the row that keeps the command honest: the two patterns it
    // cannot decide are named as such where a reader chooses one.
    expect(row!, 'the --pattern row no longer says which patterns are liveness').toContain(
      'LIVENESS',
    );
    expect(
      PATTERNS.filter((p) => p.kind === 'liveness').map((p) => p.name),
      'the liveness pair moved — the --pattern row says the LAST TWO are liveness',
    ).toEqual(PATTERN_NAMES.slice(-2));
  });
});

/**
 * The same guard on `--max-configs`, and it matters more.
 *
 * `reach` prints "exhaustive under {maxConfigs N, …}" on every absence it
 * claims. A documented default that is not the bound the walk ran under would
 * make that sentence false about the one figure the whole command hangs on.
 */
describe('the `--max-configs` default and the engine that honours it', () => {
  it('is the number `src/semantics/mc/explore.ts` actually defaults to', () => {
    expect(
      DEFAULT_MAX_CONFIGS,
      '`--max-configs`\u2019s documented default and `DEFAULT_MAX_CONFIGS` disagree',
    ).toBe(ENGINE_MAX_CONFIGS);
  });

  it('names it in the reference', () => {
    const row = DOC.split('\n').find((l) => l.startsWith('| `--max-configs N` |'));
    expect(row, 'the reference no longer renders a `--max-configs` row').toBeDefined();
    expect(row!, 'the --max-configs row no longer prints its default').toContain(
      `${DEFAULT_MAX_CONFIGS} configurations`,
    );
  });
});

/**
 * The `npm run check` section is the half of this document no spec renders.
 *
 * Everything above comes from `sysprose-spec.ts`, so the whole-document
 * comparison guards it. The check section was hand-written prose inside the
 * generator's template literal, which made that comparison tautological: it
 * compared the same sentence against itself, and the sentence was wrong — it
 * claimed `check` shared `sysprose`'s exit-code contract, when `check` exits 1
 * on a file that loaded perfectly and broke a validation rule. So the section is
 * checked against its SUBJECT instead: `scripts/sysml-check.ts`'s own `--help`.
 *
 * That file cannot be imported — it calls `runMain` at module scope, so an
 * import would run the command — so its `USAGE` template literal is read out of
 * the source text. Reading source text is the price of not executing a script,
 * and it is what makes a flag added to `check` fail here.
 */
describe("the reference's `npm run check` section and the command's own --help", () => {
  const CHECK_SRC = readFileSync(resolve(process.cwd(), 'scripts/sysml-check.ts'), 'utf8');
  const USAGE = /const USAGE = `([\s\S]*?)`;/.exec(CHECK_SRC)![1];
  const SECTION = DOC.slice(DOC.indexOf('## `npm run check`'));

  it('reads its usage out of the command, not out of prose', () => {
    expect(USAGE, 'scripts/sysml-check.ts no longer declares a USAGE literal').toContain(
      'npm run check',
    );
    expect(SECTION.length, 'docs/CLI-REFERENCE.md has no `npm run check` section').toBeGreaterThan(
      0,
    );
  });

  it('shows every synopsis line the command shows', () => {
    // Including the multi-file form: the project's own gate checks two files at
    // once, and a reference that shows one file teaches a reader to loop.
    const synopses = USAGE.split('\n')
      .map((l) => l.trim())
      .filter((l) => l.includes('npm run check --'));
    expect(synopses.length, 'USAGE shows no `npm run check` invocation').toBeGreaterThan(0);
    for (const line of synopses) expect(SECTION, `the reference shows: ${line}`).toContain(line);
  });

  it('documents every flag the command documents', () => {
    const flags = [...new Set([...USAGE.matchAll(/(?:^|\s)(--?[a-z][a-z-]*)/g)].map((m) => m[1]))]
      // `--strict`'s own doc line mentions itself; the set is what matters.
      .filter((f) => f !== '--');
    expect(flags.length, 'USAGE lists no flags').toBeGreaterThan(3);
    const missing = flags.filter((f) => !SECTION.includes(`\`${f}\``));
    expect(
      missing,
      `flags \`npm run check\` documents that the reference does not:\n${missing.join('\n')}`,
    ).toEqual([]);
  });

  it("states check's exit-code contract, in the command's own words", () => {
    expect(SECTION, 'the section quotes CHECK_EXIT_CODES').toContain(CHECK_EXIT_CODES);
    // USAGE is read as SOURCE, so what it holds is the interpolation, not the
    // value — which is the thing being asserted: the help text renders this
    // constant rather than a second copy of the sentence.
    expect(USAGE, "the command's --help interpolates the same constant").toContain(
      // Spelled in pieces so the lint rule that hunts for an accidental
      // template placeholder in a plain string does not read it as one.
      `\${${'CHECK_EXIT_CODES'}}`,
    );
    // The distinction is the whole point of stating it twice: `sysprose`'s 1 is
    // about the model, `check`'s is about the findings. A future edit that
    // collapses them back into "same exit-code contract" fails here.
    expect(SECTION).not.toContain('Same exit-code contract');
    expect(CHECK_EXIT_CODES).not.toBe(EXIT_CODES);
  });
});
