/**
 * The command table and its documentation must not drift.
 *
 * `docs/CLI-REFERENCE.md` is what a person reads before they run `npm run
 * sysprose` for the first time, and what an agent reads to find out which
 * subcommand answers its question. The dispatcher, `--help` and that document
 * are three renderings of ONE table (`scripts/lib/sysprose-spec.ts`), so the
 * only way they can disagree is if the committed document was not regenerated.
 * This is the same guard `test/unit/diagnostic-codes.test.ts` puts on the
 * diagnostic catalogue, and it fails the same way: with the command to run.
 *
 * The whole-document comparison is deliberate rather than a set of spot checks.
 * A flag whose `doc` line was reworded is a flag whose documentation is now
 * wrong, and no assertion over names alone would notice.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { STATEMENT_KINDS } from '@semantics/index';
import { renderCliReference } from '../../scripts/gen-cli-reference';
import {
  CHECK_EXIT_CODES,
  COMMANDS,
  COMMON_FLAGS,
  EXIT_CODES,
  STATEMENT_KIND_FLAG_VALUES,
  flagsFor,
} from '../../scripts/lib/sysprose-spec';

const PATH = resolve(process.cwd(), 'docs/CLI-REFERENCE.md');
const DOC = readFileSync(PATH, 'utf8');

describe('the generated command reference', () => {
  it('is what the generator renders today', () => {
    expect(
      DOC,
      'docs/CLI-REFERENCE.md is stale — run `npm run commands`',
    ).toBe(renderCliReference());
  });

  it('says it is generated, and by what', () => {
    expect(DOC.startsWith('<!-- GENERATED by scripts/gen-cli-reference.ts')).toBe(true);
    expect(DOC).toContain('npm run commands');
  });

  it('gives every subcommand a section of its own', () => {
    const documented = new Set([...DOC.matchAll(/^### `([a-z-]+)`$/gm)].map((m) => m[1]));
    const missing = COMMANDS.map((c) => c.name).filter((n) => !documented.has(n));
    expect(missing, `subcommands with no section — run \`npm run commands\`:\n${missing.join('\n')}`)
      .toEqual([]);
  });

  it('documents every flag every subcommand accepts', () => {
    const missing: string[] = [];
    for (const cmd of COMMANDS) {
      for (const f of flagsFor(cmd)) {
        // A shared flag is documented once, in the common table; an own flag is
        // documented in the subcommand's own table. Either way the reader of a
        // subcommand can find it, which is what has to stay true.
        if (!DOC.includes(`\`--${f.name}`)) missing.push(`${cmd.name} --${f.name}`);
      }
    }
    expect(missing, `undocumented flags:\n${missing.join('\n')}`).toEqual([]);
  });

  it("states the question each subcommand answers, in the spec's own words", () => {
    // Undo the table-cell escaping first: a `doc` line reaches the page as
    // written, but `|` and `<…>` have to be escaped to survive Markdown, and
    // comparing against the escaped form would be comparing against the
    // renderer rather than against the spec.
    const plain = DOC.replace(/\\\|/g, '|').replace(/&lt;/g, '<').replace(/&gt;/g, '>');
    for (const cmd of COMMANDS) expect(plain, `${cmd.name}'s question`).toContain(cmd.question);
    for (const f of COMMON_FLAGS) expect(plain, `--${f.name}'s doc line`).toContain(f.doc);
  });

  it('states the exit-code contract', () => {
    expect(DOC).toContain('0 clean');
    expect(DOC).toContain('2 usage/IO error');
  });
});

/**
 * The one value list the command table copies rather than imports.
 *
 * `scripts/lib/sysprose-spec.ts` is imported by the documentation generator and
 * by three doc guards, and it is kept free of model imports so none of them
 * pulls the core graph in to render a help line. The price is a hand-copied
 * vocabulary, and a vocabulary in two places is a vocabulary that drifts: a
 * fourth statement kind added to `@semantics/statement-kind` would be a kind
 * `--kind` silently refuses, with the reference documenting three and the
 * dispatcher accepting three. This is the assertion that makes the copy safe.
 */
describe('the `--kind` flag and the statement-kind vocabulary', () => {
  it('offers exactly the kinds the semantics module declares, in the same order', () => {
    expect(
      STATEMENT_KIND_FLAG_VALUES,
      '`requirements --kind` and `STATEMENT_KINDS` disagree about what a statement kind is',
    ).toEqual([...STATEMENT_KINDS]);
  });

  it('names every one of them in the reference', () => {
    const kindFlag = COMMANDS.flatMap((c) => c.flags).find((f) => f.name === 'kind');
    expect(kindFlag, '`requirements` no longer declares `--kind`').toBeDefined();
    // The flag's ROW, not the whole document. `toContain` over `DOC` passes on
    // any of the three by accident — `prose` is inside the word `sysprose`,
    // `prompt` inside the `prompts` section, `requirement` inside the
    // `requirements` one — so deleting this row outright would not have failed
    // it. A vocabulary guard that cannot see its own subject is not a guard.
    const row = DOC.split('\n').find((l) => l.startsWith('| `--kind KIND` |'));
    expect(row, 'the reference no longer renders a `--kind` row').toBeDefined();
    for (const kind of STATEMENT_KINDS) {
      expect(kindFlag!.doc, `--kind's doc line offers ${kind}`).toContain(kind);
      expect(row!, `the reference's --kind row names ${kind}`).toContain(kind);
    }
  });
});

/**
 * The `npm run check` section is the half of this document no spec renders.
 *
 * Everything above comes from `sysprose-spec.ts`, so the whole-document
 * comparison guards it. The check section was hand-written prose inside the
 * generator's template literal, which made that comparison tautological: it
 * compared the same sentence against itself, and the sentence was wrong — it
 * claimed `check` shared `sysprose`'s exit-code contract, when `check` exits 1
 * on a file that loaded perfectly and broke a validation rule. So the section is
 * checked against its SUBJECT instead: `scripts/sysml-check.ts`'s own `--help`.
 *
 * That file cannot be imported — it calls `runMain` at module scope, so an
 * import would run the command — so its `USAGE` template literal is read out of
 * the source text. Reading source text is the price of not executing a script,
 * and it is what makes a flag added to `check` fail here.
 */
describe("the reference's `npm run check` section and the command's own --help", () => {
  const CHECK_SRC = readFileSync(resolve(process.cwd(), 'scripts/sysml-check.ts'), 'utf8');
  const USAGE = /const USAGE = `([\s\S]*?)`;/.exec(CHECK_SRC)![1];
  const SECTION = DOC.slice(DOC.indexOf('## `npm run check`'));

  it('reads its usage out of the command, not out of prose', () => {
    expect(USAGE, 'scripts/sysml-check.ts no longer declares a USAGE literal').toContain(
      'npm run check',
    );
    expect(SECTION.length, 'docs/CLI-REFERENCE.md has no `npm run check` section').toBeGreaterThan(
      0,
    );
  });

  it('shows every synopsis line the command shows', () => {
    // Including the multi-file form: the project's own gate checks two files at
    // once, and a reference that shows one file teaches a reader to loop.
    const synopses = USAGE.split('\n')
      .map((l) => l.trim())
      .filter((l) => l.includes('npm run check --'));
    expect(synopses.length, 'USAGE shows no `npm run check` invocation').toBeGreaterThan(0);
    for (const line of synopses) expect(SECTION, `the reference shows: ${line}`).toContain(line);
  });

  it('documents every flag the command documents', () => {
    const flags = [...new Set([...USAGE.matchAll(/(?:^|\s)(--?[a-z][a-z-]*)/g)].map((m) => m[1]))]
      // `--strict`'s own doc line mentions itself; the set is what matters.
      .filter((f) => f !== '--');
    expect(flags.length, 'USAGE lists no flags').toBeGreaterThan(3);
    const missing = flags.filter((f) => !SECTION.includes(`\`${f}\``));
    expect(
      missing,
      `flags \`npm run check\` documents that the reference does not:\n${missing.join('\n')}`,
    ).toEqual([]);
  });

  it("states check's exit-code contract, in the command's own words", () => {
    expect(SECTION, 'the section quotes CHECK_EXIT_CODES').toContain(CHECK_EXIT_CODES);
    // USAGE is read as SOURCE, so what it holds is the interpolation, not the
    // value — which is the thing being asserted: the help text renders this
    // constant rather than a second copy of the sentence.
    expect(USAGE, "the command's --help interpolates the same constant").toContain(
      // Spelled in pieces so the lint rule that hunts for an accidental
      // template placeholder in a plain string does not read it as one.
      `\${${'CHECK_EXIT_CODES'}}`,
    );
    // The distinction is the whole point of stating it twice: `sysprose`'s 1 is
    // about the model, `check`'s is about the findings. A future edit that
    // collapses them back into "same exit-code contract" fails here.
    expect(SECTION).not.toContain('Same exit-code contract');
    expect(CHECK_EXIT_CODES).not.toBe(EXIT_CODES);
  });
});
